{
 "title": "vk callback",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Incoming messages rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(vk_message_new[30s])" }
   ]
  },
  {
   "title": "Wall comments rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(vk_wall_reply_new[30s])" }
   ]
  },
  {
   "title": "Group users dynamics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vk_group_join - vk_group_leave" }
   ]
  }
 ]
}